apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name.deployment }}
  labels:
    app: backend

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}