apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.db.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.db.kubernetesSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.db.awsSecretName }}