apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-external-secret
  namespace: ecommerce
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: backend-secretstore
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: eks/backend/db