apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.name.deployment }}-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}

type: Opaque

data:
  DB_PASSWORD: {{ .Values.secret.dbpassword | b64enc | quote }}