grafana:
  enabled: true

prometheus:
  enabled: true

alertmanager:
  enabled: true

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  enabled: true

defaultRules:
  create: true