name: Platform

on:
  workflow_dispatch

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: eks-learning-cluster

jobs:
  platform:
    name: Install Platform Components
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::370613533967:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
      
      - name: Setup Helm
        uses: azure/setup-helm@v4
      
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "$AWS_REGION" \
            --name "$EKS_CLUSTER_NAME"

      - name: Verify cluster access
        run: |
          kubectl get nodes

      - name: Create application Namespace
        run: |
         kubectl create namespace ecommerce --dry-run=client -o yaml | kubectl apply -f -

      - name: Add Helm Repositories
        run: |
          helm repo add external-secrets https://charts.external-secrets.io 
          helm repo add eks https://aws.github.io/eks-charts 
          helm repo update

      - name: Install External secret Operator
        run: |
          helm upgrade --install external-secrets \
          external-secrets/external-secrets \
          --namespace external-secrets \
          --create-namespace \
          --set serviceAccount.create=true \
          --set serviceAccount.name=external-secrets \ 
          --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::370613533967:role/external-secrets-role

      - name: Verify External Secret Operator
        run: |
          kubectl get pods \
            -n external-secrets

          kubectl get serviceaccount \ 
            external-secrets \ 
            -n external-secrets \ 
            -o yaml

      - name: Install AWS LoadBalancer Controller
        run: |
          VPC_ID=$(aws eks describe-cluster \ 
          --name "$EKS_CLUSTER_NAME" \ 
          --region "$AWS_REGION" \ 
          --query 'cluster.resourcesVpcConfig.vpcId' \ 
          --output text)

          helm upgrade --install aws-load-balancer-controller \ 
          eks/aws-load-balancer-controller \ 
          --namespace kube-system \ 
          --set clusterName="$EKS_CLUSTER_NAME" \ 
          --set region="$AWS_REGION" \ 
          --set vpcId="$VPC_ID" \ 
          --set serviceAccount.create=true \ 
          --set serviceAccount.name=aws-load-balancer-controller \ 
          --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::370613533967:role/AmazonEKSLoadBalancerControllerRole

      - name: Verify AWS Load Balancer Controller 
        run: | 
            kubectl get pods \ 
              -n kube-system \ 
              -l app.kubernetes.io/name=aws-load-balancer-controller 
            
            kubectl get serviceaccount \ 
              aws-load-balancer-controller \ 
              -n kube-system \ 
             -o yaml 
      
      - name: Verify platform 
        run: | 
            echo "=== Nodes ===" 
            kubectl get nodes 

            echo "=== External Secrets ===" 
            kubectl get pods -n external-secrets 

            echo "=== AWS Load Balancer Controller ===" 
            kubectl get pods \ 
            -n kube-system \ 
            -l app.kubernetes.io/name=aws-load-balancer-controller 

            echo "=== Application Namespace ===" 
            kubectl get namespace ecommerce
